### ISSUE TITLE
Please list names of CODEOWNERS

### ISSUE THREAD

**Issue by olekw** [bazelbuild/platforms#14]
Please list names (and, preferably, email addresses) of the people in CODEOWNERS. This will allow proper copyright attribution when this code is outside GitHub.

**Comment by katre** [comment]
It doesn't look like github's CODEOWNERS supports anything except github usernames and depot paths that a user is an owner for. What format do other projects use to give names and emails?

I am not aware that CODEOWNERS implies anything about copyright ownership.

**Comment by olekw** [comment]
Sorry, it looks like CODEOWNERS would not be the right place for that. Would it be possible for you to use an [AUTHORS](https://github.com/bazelbuild/bazel/blob/master/AUTHORS) file like Bazel does?

**Comment by aiuto** [comment]
@olekw How does Debian intend to use this file?

Everyone who contributes has to sign Google's CLA: https://cla.developers.google.com/about/google-corporate. That grants the copyright license to Google. IANAL, so I can't advise on the subtleties of how you interpret the contents, but for all of the repositories in the bazelbuild organization we treat the git log as the source of truth for contributions, rather than either AUTHORS or CONTRIBUTORS.

For the most part, we try to credit people in CONTRIBUTORS rather than adding everyone to AUTHORS.
